title = "default config"

[simulation]
[simulation.general]
n_photons = 100000 # Number of simulated photons
n_track = 100 # Number of photons which paths will be tracked 
starting_pos = [0, 0, 0] # (x, y, z) coords, where z=0 is the highest point of atmosphere
random_seed = 42 # for reproducibility

[simulation.sun]
theta_sun = 45 # Sun elevation angle [degrees]
phi_sun = 0 # Sun longitude [degrees]