[metadata]
experiment_name = "adjacency001"
description = "Demo showcasing adjacency effect"

[engine]
num_photons = 1_000_000
batch_size = 100_000
cpu_cores = 4

[source]
theta_sun_deg = 30

[geometry]
domain_size_x_km = 100
domain_size_y_km = 100

[detectors]
num_full_paths = 0
incident_flux_heights_km = [1e-5, 4.0]

[output]
save_incident_flux_maps = true
overwrite = true
save_plots = true


[[layer]]
z_range_km = [0, 4]
materials = [
    {type = "dark-clouds", weight = 1.0}
]

[surface]
name = "split-half-x"
material_left = "snow"
material_right = "ocean"