[metadata]
experiment_name = "simulation001"
description = "A demo simulation."

[engine]
num_photons = 10_000_000
batch_size = 100_000
random_seed = 42
cpu_cores = 4

[source]
theta_sun_deg = 0
phi_sun_deg = 30
wavelength_nm = 530

[geometry]
domain_size_x_km = 100
domain_size_y_km = 100
boundary_condition = "periodic"

[detectors]
vertical_flux_resolution_km = 1.0
map2d_resolution_km = 1.0
num_full_paths = 200

[output]
save_flux_maps = true
save_vertical_profile = true
save_boundary_flux_maps = true
save_photon_paths = true 
save_heating_rates = true
overwrite = true
path = 'results'

[surface_materials]
    [surface_materials.snow]
    albedo = 0.85
    reflection = {type = "lambertian"}
    [surface_materials.ocean]
    albedo = 0.01
    reflection = {type = "mirror", roughness = 0.0}


[atmosphere_materials]
    [atmosphere_materials.air]
    extinction_coeff_per_km = 0.01
    ssa = 0.9
    scattering = {type = "hg", g = 0}
    [atmosphere_materials.light-clouds]
    extinction_coeff_per_km = 1
    ssa = 0.999999
    scattering = {type = "hg", g = 0.85}
    [atmosphere_materials.dark-clouds]
    extinction_coeff_per_km = 5
    ssa = 0.999999
    scattering = {type = "hg", g = 0.85}

[[layer]]
z_range_km = [0, 10]
materials = [
    {type = "dark-clouds", weight = 1.0}
]

[surface]
name = "split-half-x"
material_left = "snow"
material_right = "ocean"

# [surface]
# name = "circle"
# radius_km = "20"
# material_in = "snow"
# material_out = "ocean"

# [surface]
# name = "checkerboard"
# tile_size_km = 10
# material_a = "snow"
# material_b = "ocean"