[metadata]
experiment_name = "default"
description = "Default minimal simulation parameters."

[engine]
num_photons = 100_000
batch_size = 100_000
random_seed = 42
cpu_cores = 4
resume_from_checkpoint = false
photon_survivaL_chance = 0.1
photon_weight_treshold = 1e-4

[source]
theta_sun_deg = 0
phi_sun_deg = 0 
wavelength_nm = 530

[geometry]
domain_size_x_km = 100
domain_size_y_km = 100
boundary_condition = "periodic"

[detectors]
active = []
vertical_profiles_resolution_km = 1.0
horizontal_maps_resolution_km = 1.0
num_full_paths = 200
flux_maps_z_levels_km = []

[output]
save_plots = false
overwrite = false
path = "results"

[surface_materials.default_surface]
albedo = 0.5
reflection = {type = "lambertian"}

[atmosphere_materials.default_air]
extinction_coeff_per_km = 0.01
ssa = 0.9
scattering = {type = "isotropic"}