[metadata]
experiment_name = "default"
description = "Default minimal simulation parameters."

[engine]
num_photons = 100_000
batch_size = 100_000
random_seed = 42
cpu_cores = 4
resume_from_checkpoint = false

[source]
theta_sun_deg = 0
phi_sun_deg = 0 
wavelength_nm = 530

[geometry]
domain_size_x_km = 100
domain_size_y_km = 100
boundary_condition = "periodic"

[detectors]
vertical_profiles_resolution_km = 1.0
horizontal_maps_resolution_km = 1.0
num_full_paths = 200
incident_flux_heights_km = []

[output]
save_absorption_maps = false
save_incident_flux_maps = false
save_vertical_profiles = false
save_photon_paths = false 
save_plots = false
overwrite = false
path = "results"

[surface_materials.default-surface]
albedo = 0.5
reflection = {type = "lambertian"}

[atmosphere_materials.default-air]
extinction_coeff_per_km = 0.01
ssa = 0.9
scattering = {type = "isotropic"}